[package]
name = "akplugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
bindgen = "0.64"

[dependencies]
reqwest = { version = "0.11.14", features = ["blocking", "json"] }
